package dev.etdmnet.turn

/**
 * Platform-neutral description of a single TURN/STUN server.
 *
 * Both [transport-webrtc-jvm] and [transport-webrtc-android] consume this type
 * indirectly: the helper functions [toJvmIceServer] (extension defined in the
 * JVM transport) and [toAndroidIceServer] (extension defined in the Android
 * transport) convert it to the platform-specific ICE server class.
 *
 * Keeping this type free of any platform/transport dependency means it can
 * also be serialized over the wire (e.g. fetched from your auth backend) and
 * used by a future iOS transport identically.
 *
 * @property url       Full RFC 7064/7065 URL, e.g.
 *                     `turn:turn.example.com:3478?transport=udp` or
 *                     `turns:turn.example.com:5349`.
 * @property username  TURN long-term credential username (`null` for STUN).
 * @property credential TURN long-term credential password (`null` for STUN).
 */
data class IceServerSpec(
    val url: String,
    val username: String? = null,
    val credential: String? = null,
) {
    /** True when this entry needs credentials (any `turn:`/`turns:` URL). */
    val isTurn: Boolean get() = url.startsWith("turn:") || url.startsWith("turns:")

    /** True when this entry is plain STUN (no credentials needed). */
    val isStun: Boolean get() = url.startsWith("stun:") || url.startsWith("stuns:")
}

/**
 * High-level helper for assembling an ICE server list with sensible defaults.
 *
 * Typical usage in production:
 * ```kotlin
 * val ice = TurnConfig.builder()
 *     .addPublicStuns()                                // Google + Cloudflare STUN
 *     .addTurn("turn.example.com", 3478, "u", "p")     // your coturn (UDP)
 *     .addTurns("turn.example.com", 5349, "u", "p")    // your coturn (TLS)
 *     .build()
 *
 * val transport = WebRtcTransport.connect(
 *     signalingUrl = ...,
 *     roomId       = ...,
 *     localPeerId  = ...,
 *     iceServers   = ice.toJvmIceServers(),
 * )
 * ```
 *
 * The [TurnCredentialProvider] interface (below) lets you plug in time-limited
 * credentials generated by your backend — the recommended approach for any
 * production deployment, since long-term credentials in app binaries can be
 * extracted and abused.
 */
class TurnConfig private constructor(val servers: List<IceServerSpec>) {

    fun toList(): List<IceServerSpec> = servers

    class Builder internal constructor() {
        private val out = mutableListOf<IceServerSpec>()

        /** Add Google's public STUN endpoints (no credentials required). */
        fun addGoogleStun(): Builder = apply {
            out += IceServerSpec("stun:stun.l.google.com:19302")
            out += IceServerSpec("stun:stun1.l.google.com:19302")
        }

        /** Add Cloudflare's public STUN endpoint. */
        fun addCloudflareStun(): Builder = apply {
            out += IceServerSpec("stun:stun.cloudflare.com:3478")
        }

        /** Convenience: add a curated set of well-known public STUN servers. */
        fun addPublicStuns(): Builder = addGoogleStun().addCloudflareStun()

        /** Add a custom STUN endpoint. */
        fun addStun(host: String, port: Int = 3478, tls: Boolean = false): Builder = apply {
            val scheme = if (tls) "stuns" else "stun"
            out += IceServerSpec("$scheme:$host:$port")
        }

        /** Add a UDP TURN endpoint with long-term credentials. */
        fun addTurn(host: String, port: Int = 3478, username: String, credential: String): Builder = apply {
            out += IceServerSpec(
                url = "turn:$host:$port?transport=udp",
                username = username,
                credential = credential,
            )
        }

        /** Add a TCP TURN endpoint with long-term credentials (useful when UDP is blocked). */
        fun addTurnTcp(host: String, port: Int = 3478, username: String, credential: String): Builder = apply {
            out += IceServerSpec(
                url = "turn:$host:$port?transport=tcp",
                username = username,
                credential = credential,
            )
        }

        /** Add a TURNS (TLS over TCP) endpoint — works through most corporate firewalls. */
        fun addTurns(host: String, port: Int = 5349, username: String, credential: String): Builder = apply {
            out += IceServerSpec(
                url = "turns:$host:$port?transport=tcp",
                username = username,
                credential = credential,
            )
        }

        /** Add an arbitrary, pre-built [IceServerSpec]. */
        fun add(spec: IceServerSpec): Builder = apply { out += spec }

        fun build(): TurnConfig = TurnConfig(out.toList())
    }

    companion object {
        fun builder(): Builder = Builder()

        /**
         * Default ICE list for development: Google + Cloudflare STUN only.
         * **Do not ship to production** — strict-NAT users will fail without TURN.
         */
        val DEV_DEFAULT: TurnConfig = builder().addPublicStuns().build()
    }
}

/**
 * Strategy for issuing TURN credentials at runtime.
 *
 * In production you should **never** embed long-term TURN credentials in your
 * app binary. Instead, expose a small endpoint in your backend that:
 *
 * 1. Authenticates the user (their existing login session is enough).
 * 2. Generates short-lived (HMAC-SHA1) credentials for `coturn`'s
 *    `lt-cred-mech` with a 1–4 hour TTL.
 * 3. Returns `{ username, credential, ttlSeconds, urls }`.
 *
 * See `deploy/coturn/turnserver.conf` for the matching server configuration
 * and `deploy/coturn/README.md` for an end-to-end recipe.
 */
fun interface TurnCredentialProvider {
    /**
     * @return a [TurnConfig] valid for at least [TurnCredentials.ttlSeconds] seconds.
     */
    suspend fun fetch(): TurnCredentials
}

data class TurnCredentials(
    val username: String,
    val credential: String,
    val ttlSeconds: Long,
    val urls: List<String>,
) {
    /** Materialize into a [TurnConfig] usable by the transport modules. */
    fun toTurnConfig(includePublicStun: Boolean = true): TurnConfig {
        val b = TurnConfig.builder()
        if (includePublicStun) b.addPublicStuns()
        for (u in urls) b.add(IceServerSpec(u, username, credential))
        return b.build()
    }
}
